language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer install
  - composer global require phpmetrics/phpmetrics:~2
script:
  - bin/phpunit
  - phpmetrics --report-html=build/metric --git --quiet src\